server:
  port: 8080

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/api-football
    url: jdbc:postgresql://postgres:5432/api-football
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
  data:
    redis:
      #host: localhost
      host: redis
      port: 6379

api:
  football:
    base-url: https://v3.football.api-sports.io
    api-key: ${API_FOOTBALL_KEY}
